name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Increment version
        id: version
        run: |
          # Read current version
          VERSION=$(cat version.txt)
          # Split into major, minor, and patch numbers
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          # Save new version
          echo "$NEW_VERSION" > version.txt
          # Set output for later steps
          echo "VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "chore: bump version to ${{ steps.version.outputs.VERSION }}"
          git push

      - name: Update HTML version
        run: |
          # Update page title
          sed -i "s/<title>HLS Playlist Manifests Viewer<\/title>/<title>HLS Playlist Manifests Viewer v${{ steps.version.outputs.VERSION }}<\/title>/" public/index.html
          # Update h1
          sed -i "s/<h1>Simple HLS Playlist Manifests Viewer<\/h1>/<h1>Simple HLS Playlist Manifests Viewer v${{ steps.version.outputs.VERSION }}<\/h1>/" public/index.html
          # Update footer
          sed -i "s/<p>HLS Manifest Viewer<\/p>/<p>HLS Manifest Viewer v${{ steps.version.outputs.VERSION }}<\/p>/" public/index.html

      - name: Copy files to deployment directory
        run: |
          mkdir -p dist
          cp public/* dist/
          cp README.md dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true 